# Generated by Django 6.0.2 on 2026-02-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите наименование категории",
                max_length=255,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                help_text="Введите ваше имя", max_length=255, verbose_name="Клиент"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование товара",
                max_length=255,
                verbose_name="Товар",
            ),
        ),
    ]
